class LocalizationManager:
    """Manages language settings and provides translated strings."""

    def __init__(self, initial_language='en'):
        self.language_data = {
            'en': {
                # App & Global
                'app_title': "Course Program Generator",
                'browse': "Browse...",
                'back': "Back",
                'error': "Error",
                'info': "Info",
                'warning': "Warning",
                'confirm_delete': "Confirm Delete",
                'confirm_delete_msg': "Are you sure you want to delete this requirement?",
                'feedback_btn': "Feedback",
                'feedback_title': "Provide Feedback",
                'feedback_instruction': "Please choose your preferred method to send feedback.",
                'feedback_open_email_btn': "Open Email App",
                'feedback_copy_email_btn': "Copy Email Address",
                'feedback_copied_confirm': "halil.nebioglu@ozu.edu.tr Copied to clipboard!",

                # Screen 1: Setup
                'screen1_welcome': "Welcome!",
                'screen1_select_file': "Select the offered courses file (e.g., course_offered_2425F.xls).",
                'load_and_continue': "Load Courses and Continue",
                'file_not_found_msg': "File not found! Please check the path.",
                'file_load_error_msg': "Failed to load or parse courses file:\n{e}",

                # Screen 2: Builder
                'screen2_title': "Requirement Builder",
                'available_courses_label': "Available Courses (Double-click to add)",
                'edit_req_label': "Edit Selected Requirement",
                'req_name_label': "Requirement Name:",
                'needed_label': "Needed:",
                'add_selected_btn': "-> Add Selected",
                'remove_selected_btn': "<- Remove Selected",
                'candidate_courses_label': "Candidate Courses:",
                'program_reqs_label': "Program Requirements",
                'new_blank_req_btn': "New Blank Requirement",
                'delete_selected_btn': "Delete Selected",
                'quick_add_req_label': "Quick Add Requirement",
                'add_btn': "Add",
                'continue_to_config': "Continue to Final Configuration",
                'save_to_json': "Save to JSON",
                'load_last_session': "Load Last Session",
                'load_from_json': "Load from JSON",
                'select_template_msg': "Please select a template from the list first.",
                'req_delete_warning': "Please select a requirement to delete.",
                'req_add_course_warning': "Please create or select a requirement first.",
                'req_select_courses_warning': "Please select one or more courses from 'Available Courses'.",
                'req_remove_courses_warning': "Please select courses from 'Candidate Courses' to remove.",
                'reqs_saved_msg': "Requirements saved to {filename}",
                'reqs_loaded_msg': "Loaded {count} requirements.",
                'no_last_session_msg': "No last session file found to load.",
                'min_one_req_error': "You must create or load at least one requirement.",
                'no_offered_courses_warning': "No offered courses found for the codes in '{filename}'. An empty requirement was created.",
                'format_error_title': "Format Error",
                'format_error_msg': "The selected Excel file must contain a column named 'Ders' or 'Course'.",

                # Screen 3: Generation
                'screen3_title': "Final Configuration & Generation",
                'gen_params_label': "Generation Parameters",
                'min_max_credits_label': "Min/Max Credits:",
                'load_cached_label': "Load cached programs if available",
                'output_params_label': "Output Parameters",
                'limit_programs_label': "Limit Programs:",
                'sort_by_label': "Sort By:",
                'descending_label': "Descending",
                'filtering_label': "Filtering",
                'day_conds_label': "Day Conditions:",
                'exclude_courses_label': "Exclude Courses:",
                'include_one_label': "Include At Least One:",
                'must_have_label': "Must Have Courses:",
                'generate_btn': "GENERATE PROGRAMS",
                'generating_btn': "Generating...",
                'save_output_btn': "Save Output As...",
                'cancel_btn': "Cancel",
                'cancelling_btn': "Cancelling...",
                'output_log_label': "Output Log",
                'no_output_found_warning': "No auto-saved output file found. Please generate programs first.",
                'output_copied_msg': "Output file copied to:\n{path}",
                'gen_complete_log': "\n--- GENERATION COMPLETE ---",
                'gen_cancelled_log': "\n--- GENERATION CANCELLED BY USER ---",
                'gen_config_updated_log': "Configuration updated. Starting generation process...\n",
                'gen_error_log': "\n--- AN ERROR OCCURRED ---\n{e}",
                'gen_value_error_log': "\n--- AN ERROR OCCURRED ---\nError: Please ensure Min/Max Credits and Limit Programs are valid numbers.",

                # Tooltips
                'credits_tooltip': "Set the desired range for total ECTS credits in a program.\nLeave empty to use defaults (30-42).",
                'limit_tooltip': "The maximum number of valid programs to display.\nLeave empty for NO LIMIT.",
                'sort_tooltip': "How to sort the final list. Enter a key name.\nExample: total_days, total_credits, total_hours, total_courses",
                'cache_tooltip': "If checked, the app will load pre-calculated programs if the\ncourse list, requirements, and credit limits haven't changed,\nsaving significant time. Uncheck to force a new calculation.",
                'day_num_tooltip': "Filter by number of days (e.g., <=3)",
                'day_cycle_tooltip': "Cycle states for {day}:\n  Empty: Don't care\n  Checked (✔): Must include\n  Crossed (✘): Must exclude",
                'exclude_tooltip': "Programs with ANY of these courses will be removed. Comma-separated.\nExample: CS 447.A, ACC 201.A",
                'include_tooltip': "Programs must have AT LEAST ONE of these. Comma-separated.\nExample: BUS 302.A, ECO 410.A",
                'must_tooltip': "Programs MUST have ALL of these courses. Comma-separated.\nExample: CS 333.A, HIST 101.A",

                # Program Printer
                'program_header': "\nProgram {index}:\n",
                'courses_header': "Courses:",
                'total_credits_header': "Total Credits: {credits}\n",
                'total_days_header': "Total Days: {days}\n",
                'total_hours_header': "Total Hours: {hours:.2f}\n",
                'weekly_schedule_header': "Weekly Schedule:\n",
                'time_header': "Time",
                'day_names': ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
                'filter_log': "Filter functions: {desc}\n",
                'sort_log': "Sorted by: {desc}{rev}\n",
                'total_programs_log': "Total programs found: {count}\n",
                'displaying_top_log': "Displaying top {count}:\n",

                # --- NEW: Sort By Options ---
                'sort_by_none': "(Default)",
                'sort_by_total_days': "Total Days",
                'sort_by_total_credits': "Total Credits",
                'sort_by_total_hours': "Total Hours",
                'sort_by_total_courses': "Total Courses",

                # --- NEW: Filter Descriptions ---
                'filter_desc_total_days': "Total days {op} {val}",
                'filter_desc_must_be_on': "Must be on: {days}",
                'filter_desc_must_not_be_on': "Must NOT be on: {days}",
                'filter_desc_excluding': "Excluding courses: {courses}",
                'filter_desc_including_one': "Including at least one of: {courses}",
                'filter_desc_including_all': "Must include all: {courses}",
                'filter_desc_and': " and ",

                # Predefined Requirement & Category Names
                'cat_business': "Business Administration",
                'cat_cs': "Computer Science",
                'cat_general': "General",
                'cat_anth': "Anthropology",
                'cat_baf': "International Finance",
                'cat_econ': "Economics",
                'cat_ent': "Entrepreneurship",
                'cat_ibus': "International Trade and Business",
                'cat_ir': "International Relations",
                'cat_mis': "Management Information Systems",
                'cat_psyc': "Psychology",
                'cat_law': "Law",
                'cat_ai': "Artificial Intelligence and Data Engineering",
                'cat_avm': "Aviation Management",
                'cat_ce': "Civil Engineering",
                'cat_code': "Communication Design",
                'cat_ee': "Electrical and Electronics Engineering",
                'cat_gca': "Gastronomy and Culinary Arts",
                'cat_hman': "Hotel Management",
                'cat_ide': "Industrial Design",
                'cat_ie': "Industrial Engineering",
                'cat_intar': "Interior Architecture and Environmental Design",
                'cat_plt': "Professional Flight",
                'baanth_faculty_elective': "BAANTH - Faculty Elective",
                'baanth_free_elective': "BAANTH - Free Elective",
                'baanth_program_elective': "BAANTH - Program Elective",
                'babaf_free_elective': "BABAF - Free Elective",
                'babaf_program_elective': "BABAF - Program Elective",
                'babus_area_elective': "BABUS - Specialization Area Elective",
                'babus_free_elective': "BABUS - Free Elective",
                'babus_ss_elective': "BABUS - Social Sciences Elective",
                'babus_fin_elective': "BABUS - Program Elective (FIN)",
                'babus_mgmt_elective': "BABUS - Program Elective (MGMT)",
                'babus_mis_elective': "BABUS - Program Elective (MIS)",
                'babus_mktg_elective': "BABUS - Program Elective (MKTG)",
                'babus_oper_elective': "BABUS - Program Elective (OPER)",
                'baecon_program_elective': "BAECON - Program Elective",
                'baecon_free_elective': "BAECON - Free Elective",
                'baent_free_elective': "BAENT - Free Elective",
                'baent_program_elective': "BAENT - Program Elective",
                'baent_ss_elective': "BAENT - Social Sciences Elective",
                'baibus_free_elective': "BAIBUS - Free Elective",
                'baibus_program_elective': "BAIBUS - Program Elective",
                'baibus_sfl_elective': "BAIBUS - Second Foreign Language Elective",
                'bair_free_elective': "BAIR - Free Elective",
                'bair_program_elective': "BAIR - Program Elective",
                'bair_sfl_elective': "BAIR - Second Foreign Language Elective",
                'bamis_free_elective': "BAMIS - Free Elective",
                'bamis_program_elective': "BAMIS - Program Elective",
                'bapsyc_non_faculty_elective': "BAPSYC - Non-Faculty Elective",
                'bapsyc_non_program_elective': "BAPSYC - Non-Program Elective",
                'bapsyc_program_elective': "BAPSYC - Program Elective",
                'bapsyc_free_elective': "BAPSYC - Free Elective",
                'blaw_cert_elective': "BLAW - Certificate Elective",
                'blaw_free_elective': "BLAW - Free Elective",
                'blaw_restricted_elective': "BLAW - Restricted Elective",
                'bsai_cert_elective': "BSAI - FE Certificate Elective",
                'bsai_ss_elective': "BSAI - FE Social Sciences Elective",
                'bsai_free_elective': "BSAI - Free Elective",
                'bsai_program_elective': "BSAI - Program Elective",
                'bsavm_faculty_elective': "BSAVM - Faculty Elective",
                'bsavm_free_elective': "BSAVM - Free Elective",
                'bsce_cert_elective': "BSCE - FE Certificate Elective",
                'bsce_free_elective': "BSCE - FE Free Elective",
                'bsce_program_elective': "BSCE - FE Program Elective",
                'bsce_ss_elective': "BSCE - FE Social Sciences Elective",
                'bscode_free_elective': "BSCODE - Free Elective",
                'bscode_non_faculty_elective': "BSCODE - Non-Faculty Elective",
                'bscode_program_elective': "BSCODE - Program Elective",
                'bscs_program_elective': "BSCS - Program Elective",
                'bscs_ss_elective': "BSCS - FE Social Science Elective",
                'bscs_cert_elective': "BSCS - FE Certificate Elective",
                'bscs_free_elective': "BSCS - FE Free Elective",
                'bsee_cert_elective': "BSEE - FE Certificate Elective",
                'bsee_free_elective': "BSEE - FE Free Elective",
                'bsee_ss_elective': "BSEE - FE Social Sciences Elective",
                'bsee_program_elective': "BSEE - Program Elective",
                'bsgca_free_elective': "BSGCA - Free Elective",
                'bsgca_program_elective': "BSGCA - Program Elective",
                'bsgca_ss_restricted_elective': "BSGCA - Social Sciences Restricted Elective",
                'bshman_free_elective': "BSHMAN - Free Elective",
                'bshman_program_elective': "BSHMAN - Program Elective",
                'bshman_sfl_elective': "BSHMAN - Second Foreign Language Elective",
                'bshman_ss_restricted_elective': "BSHMAN - Social Sciences Restricted Elective",
                'bside_free_elective': "BSIDE - Free Elective",
                'bside_program_elective': "BSIDE - Program Elective",
                'bsie_cert_elective': "BSIE - FE Certificate Elective",
                'bsie_free_elective': "BSIE - FE Free Elective",
                'bsie_ss_elective': "BSIE - FE Social Sciences Elective",
                'bsie_program_elective': "BSIE - Program Elective",
                'bsintar_free_elective': "BSINTAR - Free Elective",
                'bsintar_non_faculty_elective': "BSINTAR - Non-Faculty Elective",
                'bsintar_program_elective': "BSINTAR - Program Elective",
                'bsplt_faculty_elective': "BSPLT - Faculty Elective",
                'bsplt_free_elective': "BSPLT - Free Elective",
                'tll101': "TLL 101 Offered Branches",
                'tll102': "TLL 102 Offered Branches",
                'eng101': "ENG 101 Offered Branches",
                'eng102': "ENG 102 Offered Branches",
                'hist201': "HIST 201 Offered Branches",
                'hist202': "HIST 202 Offered Branches",
                'math101': "MATH 101 Offered Branches",
                'math101r': "MATH 101R Offered Branches",
                'custom_file_option': "Add from Custom File...",

                # Day names for UI
                'day_monday': "Monday",
                'day_tuesday': "Tuesday",
                'day_wednesday': "Wednesday",
                'day_thursday': "Thursday",
                'day_friday': "Friday",
                'day_saturday': "Saturday",
                'day_sunday': "Sunday",
                'day_mon_short': "Mo",
                'day_tue_short': "Tu",
                'day_wed_short': "We",
                'day_thu_short': "Th",
                'day_fri_short': "Fr",
                'day_sat_short': "Sa",
                'day_sun_short': "Su",

                # --- NEW: Cache Management ---
                'cache_mgmt_label': "Cache Management",
                'clear_program_cache_label': "Clear Program Cache (.pkl)",
                'clear_saved_outputs_label': "Clear Saved Outputs (.txt)",
                'clear_cache_btn': "Clear Selected Files",
                'confirm_clear_title': "Confirm Deletion",
                'confirm_clear_msg': "Are you sure you want to permanently delete the selected files?\n\nThis action cannot be undone.",
                'clear_success_msg': "Successfully cleared:\n{cleared_items}",
                'nothing_to_clear_msg': "No items were selected to clear.",
                'cleared_caches_item': "- Program Caches",
                'cleared_outputs_item': "- Saved Outputs",

            },
            'tr': {
                # App & Global
                'app_title': "Ders Programı Oluşturucu",
                'browse': "Gözat...",
                'back': "Geri",
                'error': "Hata",
                'info': "Bilgi",
                'warning': "Uyarı",
                'confirm_delete': "Silmeyi Onayla",
                'confirm_delete_msg': "Bu gereksinimi silmek istediğinizden emin misiniz?",
                'feedback_btn': "Geri Bildirim",
                'feedback_title': "Geri Bildirim Sağla",
                'feedback_instruction': "Geri bildirim göndermek için tercih ettiğiniz yöntemi seçin.",
                'feedback_open_email_btn': "E-posta Uygulamasını Aç",
                'feedback_copy_email_btn': "E-posta Adresini Kopyala",
                'feedback_copied_confirm': "halil.nebioglu@ozu.edu.tr Panoya kopyalandı!",

                # Screen 1: Setup
                'screen1_welcome': "Hoş Geldiniz!",
                'screen1_select_file': "Açılan dersler dosyasını seçin (örn: course_offered_2425F.xls).",
                'load_and_continue': "Dersleri Yükle ve Devam Et",
                'file_not_found_msg': "Dosya bulunamadı! Lütfen yolu kontrol edin.",
                'file_load_error_msg': "Ders dosyası yüklenirken veya işlenirken hata oluştu:\n{e}",

                # Screen 2: Builder
                'screen2_title': "Gereksinim Oluşturucu",
                'available_courses_label': "Mevcut Dersler (Eklemek için çift tıklayın)",
                'edit_req_label': "Seçili Gereksinimi Düzenle",
                'req_name_label': "Gereksinim Adı:",
                'needed_label': "Gerekli Sayı:",
                'add_selected_btn': "-> Seçileni Ekle",
                'remove_selected_btn': "<- Seçileni Çıkar",
                'candidate_courses_label': "Aday Dersler:",
                'program_reqs_label': "Program Gereksinimleri",
                'new_blank_req_btn': "Yeni Boş Gereksinim",
                'delete_selected_btn': "Seçileni Sil",
                'quick_add_req_label': "Hızlı Gereksinim Ekle",
                'add_btn': "Ekle",
                'continue_to_config': "Son Yapılandırmaya Devam Et",
                'save_to_json': "JSON'a Kaydet",
                'load_last_session': "Son Oturumu Yükle",
                'load_from_json': "JSON'dan Yükle",
                'select_template_msg': "Lütfen önce listeden bir şablon seçin.",
                'req_delete_warning': "Lütfen silmek için bir gereksinim seçin.",
                'req_add_course_warning': "Lütfen önce bir gereksinim oluşturun veya seçin.",
                'req_select_courses_warning': "'Mevcut Dersler' listesinden bir veya daha fazla ders seçin.",
                'req_remove_courses_warning': "'Aday Dersler' listesinden çıkarılacak dersleri seçin.",
                'reqs_saved_msg': "Gereksinimler şuraya kaydedildi: {filename}",
                'reqs_loaded_msg': "{count} adet gereksinim yüklendi.",
                'no_last_session_msg': "Yüklenecek son oturum dosyası bulunamadı.",
                'min_one_req_error': "En az bir gereksinim oluşturmalı veya yüklemelisiniz.",
                'no_offered_courses_warning': "'{filename}' içindeki kodlar için açılan ders bulunamadı. Boş bir gereksinim oluşturuldu.",
                'format_error_title': "Biçim Hatası",
                'format_error_msg': "Seçilen Excel dosyası 'Ders' veya 'Course' adında bir sütun içermelidir.",

                # Screen 3: Generation
                'screen3_title': "Son Yapılandırma & Oluşturma",
                'gen_params_label': "Oluşturma Parametreleri",
                'min_max_credits_label': "Min/Maks Kredi:",
                'load_cached_label': "Varsa önbellekteki programları yükle",
                'output_params_label': "Çıktı Parametreleri",
                'limit_programs_label': "Program Limiti:",
                'sort_by_label': "Sıralama Ölçütü:",
                'descending_label': "Azalan",
                'filtering_label': "Filtreleme",
                'day_conds_label': "Gün Koşulları:",
                'exclude_courses_label': "Bu Dersleri Hariç Tut:",
                'include_one_label': "Bu Derslerden En Az Biri Olsun:",
                'must_have_label': "Bu Dersler Olmalı:",
                'generate_btn': "PROGRAMLARI OLUŞTUR",
                'generating_btn': "Oluşturuluyor...",
                'save_output_btn': "Çıktıyı Farklı Kaydet...",
                'cancel_btn': "İptal Et",
                'cancelling_btn': "İptal Ediliyor...",
                'output_log_label': "Çıktı Kayıtları",
                'no_output_found_warning': "Otomatik kaydedilmiş çıktı dosyası bulunamadı. Lütfen önce program oluşturun.",
                'output_copied_msg': "Çıktı dosyası şuraya kopyalandı:\n{path}",
                'gen_complete_log': "\n--- OLUŞTURMA TAMAMLANDI ---",
                'gen_cancelled_log': "\n--- OLUŞTURMA KULLANICI TARAFINDAN İPTAL EDİLDİ ---",
                'gen_config_updated_log': "Yapılandırma güncellendi. Oluşturma süreci başlıyor...\n",
                'gen_error_log': "\n--- BİR HATA OLUŞTU ---\n{e}",
                'gen_value_error_log': "\n--- BİR HATA OLUŞTU ---\nLütfen Min/Maks Kredi ve Program Limiti alanlarına geçerli sayılar girin.",

                # Tooltips
                'credits_tooltip': "Bir programdaki toplam AKTS kredisi için istenen aralığı ayarlayın.\nVarsayılanları (30-42) kullanmak için boş bırakın.",
                'limit_tooltip': "Görüntülenecek maksimum geçerli program sayısı.\nSINIRSIZ için boş bırakın.",
                'sort_tooltip': "Son listenin nasıl sıralanacağını belirtin. Bir anahtar kelime girin.\nÖrnek: total_days, total_credits, total_hours, total_courses",
                'cache_tooltip': "İşaretlenirse, ders listesi, gereksinimler ve kredi limitleri değişmediyse,\nuygulama önceden hesaplanmış programları yükleyerek önemli ölçüde zaman kazandırır.",
                'day_num_tooltip': "Ders olan gün sayısına göre filtrele (örn: <=3)",
                'day_cycle_tooltip': "{day} için durumlar arasında geçiş yap:\n  Boş: Fark etmez\n  İşaretli (✔): Mutlaka içermeli\n  Çapraz (✘): Mutlaka hariç tutulmalı",
                'exclude_tooltip': "Bu derslerden HERHANGİ BİRİNİ içeren programlar kaldırılacaktır. Virgülle ayırın.\nÖrnek: CS 447.A, ACC 201.A",
                'include_tooltip': "Programlar bu derslerden EN AZ BİRİNİ içermelidir. Virgülle ayırın.\nÖrnek: BUS 302.A, ECO 410.A",
                'must_tooltip': "Programlar bu derslerin TÜMÜNÜ içermelidir. Virgülle ayırın.\nÖrnek: CS 333.A, HIST 101.A",

                # Program Printer
                'program_header': "\nProgram {index}:\n",
                'courses_header': "Dersler:",
                'total_credits_header': "Toplam Kredi: {credits}\n",
                'total_days_header': "Toplam Gün: {days}\n",
                'total_hours_header': "Toplam Saat: {hours:.2f}\n",
                'weekly_schedule_header': "Haftalık Program:\n",
                'time_header': "Saat",
                'day_names': ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"],
                'filter_log': "Filtre fonksiyonları: {desc}\n",
                'sort_log': "Sıralama ölçütü: {desc}{rev}\n",
                'total_programs_log': "Toplam {count} program bulundu\n",
                'displaying_top_log': "İlk {count} program gösteriliyor:\n",

                # --- NEW: Sort By Options ---
                'sort_by_none': "(Varsayılan)",
                'sort_by_total_days': "Toplam Gün",
                'sort_by_total_credits': "Toplam Kredi",
                'sort_by_total_hours': "Toplam Saat",
                'sort_by_total_courses': "Toplam Ders",

                # --- NEW: Filter Descriptions ---
                'filter_desc_total_days': "Toplam gün {op} {val}",
                'filter_desc_must_be_on': "Zorunlu günler: {days}",
                'filter_desc_must_not_be_on': "Yasaklı günler: {days}",
                'filter_desc_excluding': "Hariç tutulan dersler: {courses}",
                'filter_desc_including_one': "Bunlardan en az biri dahil: {courses}",
                'filter_desc_including_all': "Bunların tümü zorunlu: {courses}",
                'filter_desc_and': " ve ",

                # Predefined Requirement & Category Names
                'cat_business': "İşletme",
                'cat_cs': "Bilgisayar Mühendisliği",
                'cat_general': "Genel",
                'cat_anth': "Antropoloji",
                'cat_baf': "Uluslararası Finans",
                'cat_econ': "Ekonomi",
                'cat_ent': "Girişimcilik",
                'cat_ibus': "Uluslararası Ticaret ve İşletmecilik",
                'cat_ir': "Uluslararası İlişkiler",
                'cat_mis': "Yönetim Bilişim Sistemleri",
                'cat_psyc': "Psikoloji",
                'cat_law': "Hukuk",
                'cat_ai': "Yapay Zeka ve Veri Mühendisliği",
                'cat_avm': "Havacılık Yönetimi",
                'cat_ce': "İnşaat Mühendisliği",
                'cat_code': "İletişim Tasarımı",
                'cat_ee': "Elektrik ve Elektronik Mühendisliği",
                'cat_gca': "Gastronomi ve Mutfak Sanatları",
                'cat_hman': "Otel Yöneticiliği",
                'cat_ide': "Endüstriyel Tasarım",
                'cat_ie': "Endüstri Mühendisliği",
                'cat_intar': "İç Mimarlık ve Çevre Tasarımı",
                'cat_plt': "Pilotaj",
                'baanth_faculty_elective': "BAANTH - Fakülte Seçmeli",
                'baanth_free_elective': "BAANTH - Serbest Seçmeli",
                'baanth_program_elective': "BAANTH - Program Seçmeli",
                'babaf_free_elective': "BABAF - Serbest Seçmeli",
                'babaf_program_elective': "BABAF - Program Seçmeli",
                'babus_area_elective': "BABUS - Özelleşilen Alan Seçmeli",
                'babus_free_elective': "BABUS - Serbest Seçmeli",
                'babus_ss_elective': "BABUS - Sosyal Bilimler Seçmeli",
                'babus_fin_elective': "BABUS - Program İçin Seçmeli (FIN)",
                'babus_mgmt_elective': "BABUS - Program İçin Seçmeli (MGMT)",
                'babus_mis_elective': "BABUS - Program İçin Seçmeli (MIS)",
                'babus_mktg_elective': "BABUS - Program İçin Seçmeli (MKTG)",
                'babus_oper_elective': "BABUS - Program İçin Seçmeli (OPER)",
                'baecon_program_elective': "BAECON - Program İçi Seçmeli",
                'baecon_free_elective': "BAECON - Serbest Seçmeli",
                'baent_free_elective': "BAENT - Serbest Seçmeli",
                'baent_program_elective': "BAENT - Program Seçmeli",
                'baent_ss_elective': "BAENT - Sosyal Bilimler Seçmeli",
                'baibus_free_elective': "BAIBUS - Serbest Seçmeli",
                'baibus_program_elective': "BAIBUS - Program Seçmeli",
                'baibus_sfl_elective': "BAIBUS - İkinci Yabancı Dil Seçmeli",
                'bair_free_elective': "BAIR - Serbest Seçmeli",
                'bair_program_elective': "BAIR - Program Seçmeli",
                'bair_sfl_elective': "BAIR - İkinci Yabancı Dil Seçmeli",
                'bamis_free_elective': "BAMIS - Serbest Seçmeli",
                'bamis_program_elective': "BAMIS - Program Seçmeli",
                'bapsyc_non_faculty_elective': "BAPSYC - Fakülte Dışı Seçmeli",
                'bapsyc_non_program_elective': "BAPSYC - Program Dışı Seçmeli",
                'bapsyc_program_elective': "BAPSYC - Program İçi Seçmeli",
                'bapsyc_free_elective': "BAPSYC - Serbest Seçmeli",
                'blaw_cert_elective': "BLAW - Sertifika Seçmeli",
                'blaw_free_elective': "BLAW - Serbest Seçmeli",
                'blaw_restricted_elective': "BLAW - Kısıtlı Seçmeli",
                'bsai_cert_elective': "BSAI - FE Sertifika Seçmeli",
                'bsai_ss_elective': "BSAI - FE Sosyal Bilimler Seçmeli",
                'bsai_free_elective': "BSAI - Serbest Seçmeli",
                'bsai_program_elective': "BSAI - Program Seçmeli",
                'bsavm_faculty_elective': "BSAVM - Fakülte Seçmeli",
                'bsavm_free_elective': "BSAVM - Serbest Seçmeli",
                'bsce_cert_elective': "BSCE - FE Sertifika Seçmeli",
                'bsce_free_elective': "BSCE - FE Serbest Seçmeli",
                'bsce_program_elective': "BSCE - FE Program Seçmeli",
                'bsce_ss_elective': "BSCE - FE Sosyal Bilimler Seçmeli",
                'bscode_free_elective': "BSCODE - Serbest Seçmeli",
                'bscode_non_faculty_elective': "BSCODE - Fakülte Dışı Seçmeli",
                'bscode_program_elective': "BSCODE - Program Seçmeli",
                'bscs_program_elective': "BSCS - Program İçi Seçmeli",
                'bscs_ss_elective': "BSCS - FE Sosyal Bilimler Seçmeli",
                'bscs_cert_elective': "BSCS - FE Sertifika Seçmeli",
                'bscs_free_elective': "BSCS - FE Serbest Seçmeli",
                'bsee_cert_elective': "BSEE - FE Sertifika Seçmeli",
                'bsee_free_elective': "BSEE - FE Serbest Seçmeli",
                'bsee_ss_elective': "BSEE - FE Sosyal Bilimler Seçmeli",
                'bsee_program_elective': "BSEE - Program Seçmeli",
                'bsgca_free_elective': "BSGCA - Serbest Seçmeli",
                'bsgca_program_elective': "BSGCA - Program Seçmeli",
                'bsgca_ss_restricted_elective': "BSGCA - Sosyal Bilimler Kısıtlı Seçmeli",
                'bshman_free_elective': "BSHMAN - Serbest Seçmeli",
                'bshman_program_elective': "BSHMAN - Program Seçmeli",
                'bshman_sfl_elective': "BSHMAN - İkinci Yabancı Dil Seçmeli",
                'bshman_ss_restricted_elective': "BSHMAN - Sosyal Bilimler Kısıtlı Seçmeli",
                'bside_free_elective': "BSIDE - Serbest Seçmeli",
                'bside_program_elective': "BSIDE - Program Seçmeli",
                'bsie_cert_elective': "BSIE - FE Sertifika Seçmeli",
                'bsie_free_elective': "BSIE - FE Serbest Seçmeli",
                'bsie_ss_elective': "BSIE - FE Sosyal Bilimler Seçmeli",
                'bsie_program_elective': "BSIE - Program Seçmeli",
                'bsintar_free_elective': "BSINTAR - Serbest Seçmeli",
                'bsintar_non_faculty_elective': "BSINTAR - Fakülte Dışı Seçmeli",
                'bsintar_program_elective': "BSINTAR - Program Seçmeli",
                'bsplt_faculty_elective': "BSPLT - Fakülte Seçmeli",
                'bsplt_free_elective': "BSPLT - Serbest Seçmeli",
                'tll101': "TLL 101 Açılan Şubeler",
                'tll102': "TLL 102 Açılan Şubeler",
                'eng101': "ENG 101 Açılan Şubeler",
                'eng102': "ENG 102 Açılan Şubeler",
                'hist201': "HIST 201 Açılan Şubeler",
                'hist202': "HIST 202 Açılan Şubeler",
                'math101': "MATH 101 Açılan Şubeler",
                'math101r': "MATH 101R Açılan Şubeler",
                'custom_file_option': "Özel Dosyadan Ekle...",

                # Day names for UI
                'day_monday': "Pazartesi",
                'day_tuesday': "Salı",
                'day_wednesday': "Çarşamba",
                'day_thursday': "Perşembe",
                'day_friday': "Cuma",
                'day_saturday': "Cumartesi",
                'day_sunday': "Pazar",
                'day_mon_short': "Pz",
                'day_tue_short': "Sa",
                'day_wed_short': "Ça",
                'day_thu_short': "Pe",
                'day_fri_short': "Cu",
                'day_sat_short': "Ct",
                'day_sun_short': "Pa",

                # --- NEW: Cache Management ---
                'cache_mgmt_label': "Önbellek Yönetimi",
                'clear_program_cache_label': "Program Önbelleğini Temizle (.pkl)",
                'clear_saved_outputs_label': "Kaydedilmiş Çıktıları Temizle (.txt)",
                'clear_cache_btn': "Seçilenleri Temizle",
                'confirm_clear_title': "Silmeyi Onayla",
                'confirm_clear_msg': "Seçili dosyaları kalıcı olarak silmek istediğinizden emin misiniz?\n\nBu işlem geri alınamaz.",
                'clear_success_msg': "Başarıyla temizlendi:\n{cleared_items}",
                'nothing_to_clear_msg': "Temizlenecek öğe seçilmedi.",
                'cleared_caches_item': "- Program Önbellekleri",
                'cleared_outputs_item': "- Kaydedilmiş Çıktılar",

            },
        }
        self.current_language = initial_language
        self._observers = []

    def register(self, observer_callback):
        """Register a callback function to be called on language change."""
        if observer_callback not in self._observers:
            self._observers.append(observer_callback)

    def set_language(self, language_code):
        """Set the current language and notify all observers."""
        if language_code in self.language_data and self.current_language != language_code:
            self.current_language = language_code
            for callback in self._observers:
                callback()  # Call the update method of the observer

    def get_string(self, key, **kwargs):
        """
        Retrieve a string for the given key in the current language.
        Allows for dynamic value formatting.
        """
        try:
            # Get the value, which could be a string or a list
            value = self.language_data[self.current_language].get(key, f"_{key}_")

            # *** THIS IS THE FIX ***
            # Only format if the value is a string and there are args to format with
            if isinstance(value, str) and kwargs:
                return value.format(**kwargs)

            # Otherwise, return the value directly (handles strings without placeholders and lists)
            return value

        except KeyError:
            return f"_{key}_"
        except Exception as e:
            print(f"Error in get_string for key '{key}': {e}")
            return f"_{key}_ERROR_"